from __future__ import annotations

from typing import Any

SOURCE_PROFILE_SEEDS = [
    ("Reuters", "wire", 0.95, "Global wire service"),
    ("Bloomberg", "wire", 0.96, "Global market wire"),
    ("AP", "wire", 0.92, "Newswire"),
    ("Financial Times", "wire", 0.93, "Financial press"),
    ("Wall Street Journal", "wire", 0.93, "Financial press"),
    ("CNBC", "wire", 0.89, "Business media"),
    ("Fed", "official", 0.99, "US central bank"),
    ("ECB", "official", 0.99, "Eurozone central bank"),
    ("PBOC", "official", 0.99, "China central bank"),
    ("OPEC", "official", 0.98, "Oil producer group"),
    ("IMF", "official", 0.98, "International institution"),
    ("World Bank", "official", 0.98, "International institution"),
    ("UN", "official", 0.98, "International institution"),
    ("Ministry of Commerce", "official", 0.95, "Policy source"),
    ("Macro Public Account Feed", "social", 0.68, "Curated public account /公众号 feed"),
    ("Finance KOL Digest", "social", 0.60, "Curated finance influencer feed /财经大V"),
]


DEFAULT_ASSETS = [
    ("000300.SH", "沪深300", "Index", 4000.0, 0.0, "China"),
    ("HSI", "恒生指数", "Index", 18000.0, 0.0, "Hong Kong"),
    ("IXIC", "纳斯达克100", "Index", 16000.0, 0.0, "US Growth"),
    ("GC00Y", "黄金", "Commodity", 2300.0, 0.0, "Safe Haven"),
    ("CL00Y", "WTI原油", "Commodity", 80.0, 0.0, "Energy"),
    ("DXY", "美元指数", "FX", 104.5, 0.0, "USD"),
    ("US10Y", "10年期美债收益率", "Bond", 4.5, 0.0, "Rates"),
]


MARKET_SYMBOL_MAP = {
    "000300.SH": {"source": "Yahoo Finance", "symbol": "000300.SS"},
    "HSI": {"source": "Yahoo Finance", "symbol": "^HSI"},
    "IXIC": {"source": "Yahoo Finance", "symbol": "^IXIC"},
    "GC00Y": {"source": "Yahoo Finance", "symbol": "GC=F"},
    "CL00Y": {"source": "Yahoo Finance", "symbol": "CL=F"},
    "DXY": {"source": "Yahoo Finance", "symbol": "DX-Y.NYB"},
    "US10Y": {"source": "Yahoo Finance", "symbol": "^TNX"},
}


HISTORICAL_CASES = [
    (
        "FED_POLICY",
        "2022 hawkish repricing",
        "美联储持续偏鹰，市场快速上修利率路径。",
        "美债收益率上行，成长股承压，美元走强，黄金阶段性承压。",
        0.92,
    ),
    (
        "MACRO_DATA",
        "2023 inflation re-acceleration",
        "通胀数据超预期，降息预期被推迟。",
        "收益率和美元同步走高，长久期资产回撤，红利和价值相对占优。",
        0.90,
    ),
    (
        "GEO_CONFLICT",
        "2022 Russia-Ukraine shock",
        "地缘冲突升级，能源供给风险抬升。",
        "原油和黄金受益，风险资产回撤，航运和航空承压。",
        0.94,
    ),
    (
        "ENERGY_SHOCK",
        "2023 OPEC supply cuts",
        "原油供给收缩或运输受阻。",
        "油价和能源链条上行，通胀预期被动抬升。",
        0.91,
    ),
    (
        "TRADE_TARIFF",
        "2018 tariff escalation",
        "贸易摩擦升级，出口链预期受损。",
        "半导体、制造、航运与全球风险偏好受到冲击。",
        0.89,
    ),
    (
        "TECH_BREAKTHROUGH",
        "2023 AI capex wave",
        "AI和算力突破刺激产业链资本开支预期。",
        "算力、半导体、软件和相关ETF走强，风格切向成长。",
        0.84,
    ),
    (
        "ELECTION_RISK",
        "2024 election uncertainty",
        "关键选举结果增加政策不确定性。",
        "美元、国债和黄金波动上升，政策敏感资产出现轮动。",
        0.80,
    ),
    (
        "NATURAL_DISASTER",
        "2011 Japan earthquake shock",
        "自然灾害冲击供应链和工业生产。",
        "相关地区制造业、航运和保险板块承压，部分商品波动放大。",
        0.83,
    ),
]


EVENT_LIBRARY: dict[str, dict[str, Any]] = {
    "FED_POLICY": {
        "label": "美联储政策冲击",
        "region": "US",
        "base_score": 88,
        "keywords": [
            "fed",
            "fomc",
            "powell",
            "rate hike",
            "rate cut",
            "interest rate",
            "dot plot",
            "美联储",
            "加息",
            "降息",
            "议息",
            "利率决议",
            "点阵图",
        ],
        "asset_impacts": [
            {"asset_code": "US10Y", "direction": "up", "duration": "intraday", "rationale": "利率路径重定价通常先推高长端收益率"},
            {"asset_code": "DXY", "direction": "up", "duration": "intraday", "rationale": "利率优势带动美元走强"},
            {"asset_code": "IXIC", "direction": "down", "duration": "1-3d", "rationale": "长久期成长股对贴现率最敏感"},
            {"asset_code": "GC00Y", "direction": "down", "duration": "1-3d", "rationale": "实际利率上行会压制黄金"},
            {"asset_code": "000300.SH", "direction": "down", "duration": "1-3d", "rationale": "外部流动性和风险偏好同步承压"},
        ],
        "causal_chain": [
            "政策措辞转向鹰派 -> 市场上修未来利率路径",
            "美债收益率和美元率先反应 -> 全球流动性边际收紧",
            "成长股估值受压 -> 风险资产波动放大",
            "黄金和高贝塔资产短线承压 -> 价值和防御风格相对占优",
        ],
        "risk_warning": "如果市场已经提前定价，初始波动可能在数小时内快速回吐。",
        "watchpoints": ["10年期美债收益率", "DXY", "纳指期货", "黄金"],
    },
    "MACRO_DATA": {
        "label": "宏观数据冲击",
        "region": "Global",
        "base_score": 80,
        "keywords": [
            "cpi",
            "inflation",
            "pce",
            "gdp",
            "jobs",
            "nonfarm",
            "unemployment",
            "通胀",
            "就业",
            "GDP",
            "CPI",
            "PCE",
            "非农",
            "失业率",
            "零售销售",
        ],
        "asset_impacts": [
            {"asset_code": "US10Y", "direction": "up", "duration": "intraday", "rationale": "强数据通常推升收益率并重新定价政策预期"},
            {"asset_code": "DXY", "direction": "up", "duration": "intraday", "rationale": "宏观偏强支撑美元"},
            {"asset_code": "IXIC", "direction": "down", "duration": "1-3d", "rationale": "高估值资产对利率预期高度敏感"},
            {"asset_code": "GC00Y", "direction": "mixed", "duration": "1-3d", "rationale": "通胀与实际利率渠道方向可能冲突"},
        ],
        "causal_chain": [
            "宏观数据偏热 -> 政策宽松预期降温",
            "收益率和美元上行 -> 贴现率抬升",
            "高估值资产承压 -> 风格轮动到防御和价值",
        ],
        "risk_warning": "需要区分一次性数据噪声和趋势性恶化，避免过度交易。",
        "watchpoints": ["美元指数", "美债收益率", "科技股期货", "黄金"],
    },
    "GEO_CONFLICT": {
        "label": "地缘冲突 / 战争升级",
        "region": "Middle East / Europe",
        "base_score": 92,
        "keywords": [
            "war",
            "conflict",
            "strike",
            "missile",
            "sanction",
            "military",
            "battle",
            "地缘",
            "战争",
            "冲突",
            "武装",
            "袭击",
            "制裁",
            "空袭",
            "炮击",
        ],
        "asset_impacts": [
            {"asset_code": "CL00Y", "direction": "up", "duration": "intraday", "rationale": "供应中断风险抬升原油风险溢价"},
            {"asset_code": "GC00Y", "direction": "up", "duration": "intraday", "rationale": "避险需求上升推动黄金"},
            {"asset_code": "IXIC", "direction": "down", "duration": "1-3d", "rationale": "风险偏好回落压制成长资产"},
            {"asset_code": "HSI", "direction": "down", "duration": "1-3d", "rationale": "全球风险资产同步承压"},
        ],
        "causal_chain": [
            "冲突升级 -> 供应链和能源运输风险上升",
            "原油风险溢价抬升 -> 通胀预期抬头",
            "避险资金流向黄金和美元 -> 风险资产承压",
        ],
        "risk_warning": "若冲突未扩散或快速降温，避险溢价会快速回吐。",
        "watchpoints": ["布伦特/WTI油价", "黄金", "美元", "航运与航空板块"],
    },
    "ENERGY_SHOCK": {
        "label": "能源供给冲击",
        "region": "Global",
        "base_score": 86,
        "keywords": [
            "oil",
            "gas",
            "opec",
            "pipeline",
            "refinery",
            "energy",
            "原油",
            "天然气",
            "欧佩克",
            "OPEC",
            "管道",
            "炼厂",
            "能源",
            "供应中断",
        ],
        "asset_impacts": [
            {"asset_code": "CL00Y", "direction": "up", "duration": "intraday", "rationale": "供给收缩直接利多油价"},
            {"asset_code": "GC00Y", "direction": "up", "duration": "1-3d", "rationale": "能源冲击推升通胀和避险需求"},
            {"asset_code": "US10Y", "direction": "up", "duration": "1-3d", "rationale": "通胀预期与期限溢价可能抬升"},
        ],
        "causal_chain": [
            "供给收缩或运输受阻 -> 原油和天然气价格上行",
            "能源成本上升 -> 通胀预期被动抬升",
            "权益市场承压 -> 能源链条和资源股相对受益",
        ],
        "risk_warning": "需要区分一次性扰动和持续性供给缺口。",
        "watchpoints": ["原油期货", "天然气", "能源板块", "航运成本"],
    },
    "TRADE_TARIFF": {
        "label": "贸易 / 关税 / 管制升级",
        "region": "Global",
        "base_score": 84,
        "keywords": [
            "tariff",
            "trade war",
            "export control",
            "restriction",
            "customs",
            "关税",
            "贸易战",
            "出口管制",
            "禁运",
            "制裁清单",
            "反制",
            "配额",
        ],
        "asset_impacts": [
            {"asset_code": "000300.SH", "direction": "down", "duration": "1-4w", "rationale": "出口链和风险偏好承压"},
            {"asset_code": "HSI", "direction": "down", "duration": "1-4w", "rationale": "外需和中国资产风险偏好同步受压"},
            {"asset_code": "IXIC", "direction": "down", "duration": "1-4w", "rationale": "半导体和跨境科技链受扰动"},
            {"asset_code": "DXY", "direction": "up", "duration": "1-3d", "rationale": "避险和政策不确定性往往支撑美元"},
        ],
        "causal_chain": [
            "关税或管制升级 -> 供应链和利润预期受损",
            "企业资本开支与库存决策推迟 -> 风险偏好下降",
            "出口链和科技链条受压 -> 美元和防御资产相对占优",
        ],
        "risk_warning": "若政策只停留在口头威慑而没有落地，市场冲击会明显减弱。",
        "watchpoints": ["出口链", "半导体", "航运", "美元"],
    },
    "TECH_BREAKTHROUGH": {
        "label": "重大科技突破",
        "region": "Global",
        "base_score": 74,
        "keywords": [
            "ai",
            "chip",
            "semiconductor",
            "breakthrough",
            "model",
            "quantum",
            "drug",
            "approval",
            "AI",
            "芯片",
            "半导体",
            "突破",
            "量子",
            "药物",
            "获批",
            "算力",
        ],
        "asset_impacts": [
            {"asset_code": "IXIC", "direction": "up", "duration": "1-4w", "rationale": "科技预期改善有利成长风格"},
            {"asset_code": "000300.SH", "direction": "mixed", "duration": "1-4w", "rationale": "产业链映射不一，需看落地环节"},
            {"asset_code": "HSI", "direction": "mixed", "duration": "1-4w", "rationale": "科技权重提升时可能受益，但节奏分化"},
        ],
        "causal_chain": [
            "技术突破 -> 商业化和资本开支预期上升",
            "行业利润弹性被重估 -> 成长风格和相关产业链受益",
            "若估值已经较高，需要防止利好兑现过快",
        ],
        "risk_warning": "技术新闻不等于业绩落地，需观察订单、融资和收入确认。",
        "watchpoints": ["算力链", "半导体设备", "软件平台", "相关ETF"],
    },
    "ELECTION_RISK": {
        "label": "选举 / 政策不确定性",
        "region": "Global",
        "base_score": 72,
        "keywords": [
            "election",
            "vote",
            "parliament",
            "referendum",
            "poll",
            "选举",
            "投票",
            "议会",
            "公投",
            "民调",
            "执政党",
            "反对党",
        ],
        "asset_impacts": [
            {"asset_code": "DXY", "direction": "up", "duration": "1-3d", "rationale": "不确定性通常提升美元和现金偏好"},
            {"asset_code": "US10Y", "direction": "mixed", "duration": "1-3d", "rationale": "财政与政策预期可能拉扯债券定价"},
            {"asset_code": "GC00Y", "direction": "up", "duration": "1-3d", "rationale": "政策不确定性推高避险需求"},
        ],
        "causal_chain": [
            "选举结果不确定 -> 政策路径难以定价",
            "波动率抬升 -> 防御和避险资产受益",
            "风险资产倾向于等待结果确认后再定价",
        ],
        "risk_warning": "民调和盘口预期会提前消化结果，注意事件前后不同阶段的市场反应。",
        "watchpoints": ["民调变化", "波动率", "美元", "国债"],
    },
    "NATURAL_DISASTER": {
        "label": "地震 / 洪水 / 飓风等自然灾害",
        "region": "Local / Regional",
        "base_score": 66,
        "keywords": [
            "earthquake",
            "flood",
            "hurricane",
            "disaster",
            "typhoon",
            "地震",
            "洪水",
            "飓风",
            "台风",
            "灾害",
            "滑坡",
            "停电",
            "损毁",
        ],
        "asset_impacts": [
            {"asset_code": "CL00Y", "direction": "mixed", "duration": "1-3d", "rationale": "灾害对能源供需的影响取决于地区和基础设施损毁情况"},
            {"asset_code": "GC00Y", "direction": "up", "duration": "intraday", "rationale": "风险事件常触发短线避险需求"},
            {"asset_code": "HSI", "direction": "down", "duration": "1-3d", "rationale": "区域风险偏好回落影响港股和相关供应链"},
        ],
        "causal_chain": [
            "自然灾害 -> 供应链和基础设施受损",
            "局部生产和物流中断 -> 相关行业短线承压",
            "若影响范围扩散，避险需求同步抬升",
        ],
        "risk_warning": "需要判断是否只是局部事件，还是会演化成更大范围的供应链冲击。",
        "watchpoints": ["受灾地区供应链", "保险板块", "黄金", "相关商品"],
    },
    "GENERAL": {
        "label": "一般市场事件",
        "region": "Global",
        "base_score": 52,
        "keywords": [],
        "asset_impacts": [
            {"asset_code": "000300.SH", "direction": "mixed", "duration": "1-3d", "rationale": "缺少明确方向，需要更多验证"},
        ],
        "causal_chain": [
            "信息还不足以形成高置信结论",
            "先等待二次来源和价格确认，再决定是否升级为交易信号",
        ],
        "risk_warning": "请先验证信息真实性，不要过度解读单条新闻。",
        "watchpoints": ["补充来源", "价格反应", "后续二次报道"],
    },
}
